spring:
  datasource:
    url: jdbc:h2:mem:elevdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: elevator-group
      auto-offset-reset: earliest

server:
  port: 8080
